# Default values for jupyterhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: data-science
db:
  image:      
    repository: registry:443/rhel8/postgresql-96
    tag: "latest"

jupyter:
  image:
    repository: registry:443/odh-jupyterhub/jupyterhub-img
    tag: "v0.2.2"

nbviewer:
  image:
    repository: registry:443/odh-jupyterhub/nbviewer
    tag: "latest"

spark:
  image:
    repository: registry:443/radanalyticsio/openshift-spark-py36
    tag: "2.4.5-2"
  worker:
    count: 1
  master: 
    count: 1
  notebook:
    image:
      repository: registry:443/odh-jupyterhub/s2i-spark-minimal-notebook
      tag: "py36-spark2.4.5-hadoop2.7.3"
