apiVersion: v1
kind: ConfigMap
metadata:
  name: superset
  namespace: {{ .Values.namespace }}
  labels:
    opendatahub.io/component: "true"
    component.opendatahub.io/name: superset
data:
  SUPERSET_ADMIN_USER: 'admin'
  SUPERSET_ADMIN_PASSWORD: 'admin'
  SUPERSET_ADMIN_FNAME: 'admin'
  SUPERSET_ADMIN_LNAME: 'admin'
  SUPERSET_ADMIN_EMAIL: 'admin@fab.org'
  SUPERSET_VOLUME_SIZE: '512Mi'
  SUPERSET_SQLALCHEMY_DB_URI: 'sqlite:////var/lib/superset/superset.db'
  FLASK_APP: superset
  SUPERSET_CONFIG_PATH: /etc/superset/superset_config.py
  superset_config.py: |
    import os

    MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY', '')
    SQLALCHEMY_DATABASE_URI = os.getenv('SUPERSET_SQLALCHEMY_DB_URI', '')
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SECRET_KEY = os.getenv('SUPERSET_SECRET_KEY','thisISaSECRET_1234')
    DATA_DIR = '/var/lib/superset'
