apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: superset
  namespace: {{ .Values.namespace }}
  labels:
    app: superset
    opendatahub.io/component: "true"
    component.opendatahub.io/name: superset
spec:
  replicas: 1
  selector:
    deploymentconfig: superset
  template:
    metadata:
      labels:
        app: superset
        deploymentconfig: superset
    spec:
      containers:
        - name: superset
          command:
            - /bin/sh
            - entrypoint.sh
          envFrom:
            - configMapRef:
                name: superset
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8088
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/superset
              name: superset-data
            - mountPath: /etc/superset
              name: superset-config
      volumes:
        - name: superset-data
          persistentVolumeClaim:
            claimName: superset-data
        - configMap:
            defaultMode: 420
            items:
              - key: superset_config.py
                path: superset_config.py
            name: superset
          name: superset-config
  triggers:
    - type: ConfigChange
