apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-data
  namespace: {{ .Values.namespace }}
  labels:
    opendatahub.io/component: "true"
    component.opendatahub.io/name: superset
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
